import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

function parseProfileArg(argv) {
  for (let index = 0; index < argv.length; index += 1) {
    const value = argv[index];
    if (value === '--profile') {
      const next = argv[index + 1];
      if (next && !next.startsWith('--')) {
        return next;
      }
      return '';
    }

    if (value.startsWith('--profile=')) {
      return value.slice('--profile='.length);
    }
  }

  return '';
}

function normalizeProfile(value) {
  const normalized = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/(^-|-$)/g, '');

  return normalized.length > 0 ? normalized : null;
}

const rootDir = process.cwd();
const profile = normalizeProfile(parseProfileArg(process.argv.slice(2)));
const envFileName = profile ? `.env.wings.${profile}` : '.env.wings';
const envExampleFileName = `${envFileName}.example`;
const fallbackEnvExampleFileName = '.env.wings.example';
const wingsRoot = resolve(rootDir, '.data', profile ? `wings-${profile}` : 'wings');
const directories = ['etc', 'log', 'tmp'];

for (const entry of directories) {
  mkdirSync(join(wingsRoot, entry), { recursive: true });
}

const envExamplePath = resolve(rootDir, envExampleFileName);
const fallbackEnvExamplePath = resolve(rootDir, fallbackEnvExampleFileName);
const sourceEnvExamplePath = existsSync(envExamplePath) ? envExamplePath : fallbackEnvExamplePath;
const envPath = resolve(rootDir, envFileName);
if (!existsSync(envPath)) {
  const envContent = readFileSync(sourceEnvExamplePath, 'utf8');
  writeFileSync(envPath, envContent, 'utf8');
}

const configPath = join(wingsRoot, 'etc', 'config.yml');
if (!existsSync(configPath)) {
  const expectedApiPort = profile === 'isolated' ? '8180' : '8080';

  writeFileSync(
    configPath,
    [
      '# Paste the node config generated by XyraPanel into this file.',
      '# Admin -> Nodes -> <Your Node> -> Configuration',
      '#',
      '# Important for Docker Desktop local dev:',
      '# 1) Start panel with: pnpm exec nuxt dev --host 0.0.0.0 --port 3000',
      `# 2) Use node base URL: http://host.docker.internal:${expectedApiPort}`,
      '# If the generated "remote" URL points to http://localhost:3000,',
      '# change it to http://host.docker.internal:3000 so Wings can reach the panel.',
      '#',
      '# Note: with docker socket mode, Wings data and runtime paths default to',
      '# /var/lib/pterodactyl and /run/wings on the Docker daemon host.',
      '',
    ].join('\n'),
    'utf8',
  );
}

console.log(`[wings:init] Prepared ${wingsRoot} directories.`);
console.log(`[wings:init] Ensured ${envFileName} exists.`);
console.log(`[wings:init] Wings config path: ${configPath}`);
